### ISSUE TITLE
v0.1 Editorial  checklist/wishlist

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/waci-presentation-exchange#26]
As per call 7June - updated 12 July
- [x] make sure nothing promised [here](https://wiki.trustoverip.org/display/HOME/GHP+Blueprint+Public+Review+Process) is missing
- [x] illustrative, cohesive examples (with real dids, real public keys, etc that actually work with each other)
- [x] Example completeness (each example would work in real life)
- [x] Appendix of out-of-scope topics

Minor nits:
- [x] #25 
- [x] #24

**Comment by brentzundel** [comment]
An implementation of WACI v0.1 is the first step toward getting real-world examples.
@swcurran how is BC Gov's implementation coming?

**Comment by swcurran** [comment]
At the moment, BC Gov is not planning an implementation. Within Aries Cloud Agent Python (ACA-Py) we have most of the components ready (OOB, Present Proof, BBS+, DIF PE), with the exception of DIDComm V2 support above the message envelope (which is close to being completed -- we'll have that Real Soon Now, in order to support AIP 2.0), and the V3.0 version of the present-proof protocol (which should be trivial). We'd be happy to see others move forward in completing the WACI-PEx work based on ACA-Py. However, the BC Gov Digital Trust team is focused on other deliverables and so is not planning on  doing the work for this right now.

**Comment by brianorwhatever** [comment]
>  make sure nothing promised here is missing
....the here linked in the issue promises vc issuance. v1?

**Comment by OR13** [comment]
Should addressed by https://github.com/decentralized-identity/waci-presentation-exchange/pull/128/files

**Comment by OR13** [comment]
We have added a link to test vectors, examples and implementation.... to the top level readme.
